import type { Concept, ExamBlueprint, Generator, Goal } from '@lemma/core';
import {
  type JpzVariant,
  type TaskFormat,
  JPZ_PAPERS,
  JPZ_UNREADABLE,
  VARIANT_OF_GOAL,
  evidenceFor,
  formatShares,
} from './evidence';
import { JPZ_EVIDENCE_RETRIEVED_ON } from './evidence-data';
import { JPZ_SPEC, JPZ_SPEC_SOURCE, SPEC_AREAS, SPEC_STAGE } from './spec';

/**
 * The coverage document, built from the data and from nothing else: what the official
 * specification asks, what the past papers contained, and what the app has problems for.
 * `npm run jpz:coverage` writes it to docs/cermat-coverage.md; a test fails when the file
 * and the data have drifted apart.
 */

export interface CoverageInput {
  goals: readonly Goal[];
  concepts: readonly Concept[];
  generators: readonly Generator[];
  blueprints: readonly ExamBlueprint[];
  /** Closed formats by the tag their generators carry. */
  formatTags: Readonly<Record<string, string>>;
}

const FORMAT_NAMES: Readonly<Record<TaskFormat, string>> = {
  open: 'open',
  construction: 'construction',
  truefalse: 'true/false bundle',
  choice: 'five-option choice',
  matching: 'matching bundle',
};

const VARIANT_NAMES: Readonly<Record<JpzVariant, string>> = {
  M9: 'four-year fields (grade 9)',
  M7: 'six-year grammar schools (grade 7)',
  M5: 'eight-year grammar schools (grade 5)',
};

const pct = (share: number, digits = 1): string => `${(share * 100).toFixed(digits)} %`;
const table = (header: string[], rows: (string | number)[][]): string =>
  [
    `| ${header.join(' | ')} |`,
    `|${header.map(() => '---').join('|')}|`,
    ...rows.map((row) => `| ${row.join(' | ')} |`),
  ].join('\n');

export function coverageDocument(input: CoverageInput): string {
  const { goals, concepts, generators, blueprints, formatTags } = input;
  const entrance = goals.filter((goal) => goal.kind === 'entrance');
  const conceptById = new Map(concepts.map((concept) => [concept.id, concept]));
  const generatorsOf = (id: string): Generator[] =>
    generators.filter((generator) => generator.concept === id && !generator.deprecated);
  const hasProblems = (id: string): boolean => generatorsOf(id).length > 0;
  const closedTags = Object.values(formatTags);
  const out: string[] = [];
  const push = (...lines: string[]): void => void out.push(...lines);

  push(
    '# CERMAT entrance examination — coverage matrix',
    '',
    '> Generated by `npm run jpz:coverage` from `packages/content/src/jpz/` and the concepts and',
    '> generators of the `basic` track. Do not edit by hand: change the data and generate again.',
    '',
    `Official sources were read on ${JPZ_EVIDENCE_RETRIEVED_ON}. This document says what the app's`,
    'entrance-examination content rests on, skill by skill, and where it stops.',
    '',
    '## 1. What is official and what is Lemma’s reading',
    '',
    '**Official** (the Centre’s own documents, linked below): the time limit, the points, the',
    'aids, the dates; the items of the specification of requirements; for every past task its',
    'number, its points and its format.',
    '',
    '**Lemma’s reading** (an inference, and marked as such wherever it is used): which skill a',
    'task belongs to; from that, each skill’s share of the points; the wording of the',
    'specification items, which is a paraphrase — the text that counts is the document’s.',
    '',
    '**Not in this repository**: the wording, figures or answers of any official task. The',
    'booklets are protected; the app’s problems are its own. Every paper below is a link to the',
    'official file.',
    '',
    '## 2. The examinations',
    '',
  );
  push(
    table(
      ['Goal', 'For', 'Tasks', 'Points', 'Minutes', 'Regular terms', 'Papers read', 'Weights'],
      entrance.map((goal) => [
        `\`${goal.id}\``,
        goal.title.en,
        `${goal.facts!.tasks} (${goal.facts!.open} open, ${goal.facts!.closed} closed)`,
        goal.facts!.points,
        goal.facts!.minutes,
        goal
          .facts!.terms.slice(0, 2)
          .map((term) => term.day)
          .join(', '),
        goal.papersRead,
        `${goal.provisional ? 'provisional: ' : ''}from ${evidenceFor(VARIANT_OF_GOAL[goal.id]!).readPoints} points of read tasks`,
      ]),
    ),
    '',
    'Sources of these facts:',
    '',
    ...[...new Map(entrance.flatMap((goal) => goal.facts!.sources).map((source) => [source.url, source])).values()].map(
      (source) => `- [${source.title}](${source.url})`,
    ),
    '',
    `The specification is the document for 2022/2023 (${JPZ_SPEC_SOURCE.url}); on the day it was read`,
    'the site said it applied unchanged, and had published nothing newer. Dates and rules change',
    'every year: `reviewAfter` in the goal’s facts says when to read them again.',
    '',
    '## 3. The past papers',
    '',
  );

  const variants: JpzVariant[] = ['M9', 'M7', 'M5'];
  push(
    table(
      [
        'Variant',
        'Papers classified',
        'by reading every task',
        'by keyword rules',
        'Scans, not inspected',
        'Read points',
      ],
      variants.map((variant) => {
        const evidence = evidenceFor(variant);
        return [
          `${variant} — ${VARIANT_NAMES[variant]}`,
          evidence.papersRead + evidence.papersByRules,
          evidence.papersRead,
          evidence.papersByRules,
          JPZ_UNREADABLE.filter((paper) => paper.id.startsWith(variant)).length,
          evidence.readPoints,
        ];
      }),
    ),
    '',
    `In all ${JPZ_PAPERS.length} booklets of 2017–2026 were split into tasks; for each of them the number of`,
    'tasks and the sum of points equal what its cover declares. The pilot years 2015 and 2016 were',
    'left out because the site itself says they do not match the specification in force.',
    '',
    '**Weights are computed from the papers that were read, and only from them.** The keyword',
    'rules agree with the reading on at least one skill for 81 % of tasks and on the whole set',
    'for 59 %: good enough to show where a skill occurs, not good enough to weigh it. A goal with',
    'few read papers has provisional weights, and the app says so wherever it shows them.',
    '',
    'Points by task format in the read papers:',
    '',
    table(
      ['Variant', ...Object.values(FORMAT_NAMES)],
      variants.map((variant) => {
        const shares = formatShares(variant);
        return [variant, ...(Object.keys(FORMAT_NAMES) as TaskFormat[]).map((format) => pct(shares[format]))];
      }),
    ),
    '',
  );

  push('## 4. The practice tests', '');
  for (const blueprint of blueprints.filter((entry) => entry.kind === 'entrance')) {
    const slots = blueprint.slots ?? [];
    const bundles = blueprint.bundles ?? {};
    const loose = slots.filter((slot) => !slot.bundle).reduce((sum, slot) => sum + slot.points, 0);
    const bundled = Object.values(bundles).reduce((sum, points) => sum + (points[points.length - 1] ?? 0), 0);
    push(
      `### \`${blueprint.id}\` — ${blueprint.title.en}`,
      '',
      `${slots.length} answer fields, ${blueprint.minutes} minutes, ${loose + bundled} of 50 points on a screen; ${blueprint.offScreenPoints ?? 0} points of`,
      'construction tasks are left out and the time is shortened by their share.',
      '',
      table(
        ['Task', 'Format', 'Points', 'Level', 'Skills drawn from'],
        slots.map((slot) => [
          slot.label,
          slot.format,
          slot.bundle ? `bundle \`${slot.bundle}\`: ${bundles[slot.bundle]!.join('–')}` : slot.points,
          slot.level,
          slot.skills.map((id) => `\`${id}\``).join(', '),
        ]),
      ),
      '',
    );
  }
  push(
    'A bundle is scored by how many of its parts are right, as in the 2026 answer keys. What a',
    'screen cannot reproduce: tasks marked on the whole working are checked here on the result',
    'only; the three statements of a true/false task and the three parts of a matching task are',
    'separate problems here, each with its own data, where the real test hangs them on one.',
    '',
  );

  push('## 5. Skills, goal by goal', '');
  for (const goal of entrance) {
    const variant = VARIANT_OF_GOAL[goal.id]!;
    const evidence = evidenceFor(variant);
    const tested = goal.skills.filter((skill) => skill.role === 'tested');
    const practisable = tested.filter((skill) => hasProblems(skill.id));
    const weightCovered = practisable.reduce((sum, skill) => sum + skill.weight, 0);
    const weightAll = tested.reduce((sum, skill) => sum + skill.weight, 0);
    push(
      `### \`${goal.id}\` — ${goal.title.en}`,
      '',
      `Tested skills: ${tested.length} · prerequisites: ${goal.skills.filter((skill) => skill.role === 'prerequisite').length} · beyond the examination: ${goal.skills.filter((skill) => skill.role === 'enrichment').length}. Weights from ${evidence.papersRead} read papers (${evidence.readPoints} points)${goal.provisional ? ' — **provisional**' : ''}.`,
      `Problems exist for ${practisable.length} of the ${tested.length} tested skills, carrying ${pct(weightCovered / (weightAll || 1))} of the weight.`,
      '',
      table(
        [
          'Skill',
          'Role',
          'Weight',
          'Tasks read',
          'Tasks by rules',
          'Specification',
          'Problem families',
          'Levels',
          'Closed formats',
        ],
        [...goal.skills]
          .sort((a, b) => b.weight - a.weight || a.id.localeCompare(b.id))
          .map((skill) => {
            const concept = conceptById.get(skill.id);
            const families = generatorsOf(skill.id);
            const levels = [...new Set(families.flatMap((generator) => generator.levels))].sort();
            const closed = closedTags.filter((tag) => families.some((generator) => generator.tags?.includes(tag)));
            return [
              `\`${skill.id}\` ${concept?.title.en ?? ''}`,
              skill.role,
              skill.role === 'tested' ? pct(skill.weight) : '—',
              skill.tasks.read,
              skill.tasks.rules,
              (concept?.spec ?? []).join(', ') || '—',
              concept?.paperOnly ? 'paper only' : families.length,
              levels.length > 0 ? `${levels[0]}–${levels[levels.length - 1]}` : '—',
              closed.join(', ') || '—',
            ];
          }),
      ),
      '',
    );
  }

  push(
    '## 6. The specification, item by item',
    '',
    'Parts are cumulative: B includes A, C includes A and B. "Problems" says whether a skill',
    'that lists the item has problems in the app.',
    '',
  );
  const uncovered: string[] = [];
  for (const part of ['A', 'B', 'C'] as const) {
    const items = JPZ_SPEC.filter((item) => item.part === part);
    const covered = items.filter((item) =>
      concepts.some((concept) => concept.spec?.includes(item.id) && hasProblems(concept.id)),
    );
    push(
      `### Part ${part} — expected by the end of grade ${SPEC_STAGE[part]}: ${covered.length} of ${items.length} items with problems`,
      '',
      table(
        ['Item', 'Area', 'Requirement (paraphrase)', 'Skills', 'Problems'],
        items.map((item) => {
          const listing = concepts.filter((concept) => concept.spec?.includes(item.id));
          const withProblems = listing.some((concept) => hasProblems(concept.id));
          if (!withProblems) uncovered.push(item.id);
          return [
            item.id,
            SPEC_AREAS[item.area].en,
            item.summary.en,
            listing.map((concept) => `\`${concept.id}\``).join(', ') || '—',
            withProblems ? 'yes' : listing.length > 0 ? '**no** (paper only)' : '**no**',
          ];
        }),
      ),
      '',
    );
  }

  push(
    '## 7. What is not covered',
    '',
    `- **${uncovered.length} of the ${JPZ_SPEC.length} specification items have no problems in the app**: ${uncovered.join(', ')}.`,
    '  They are mostly constructions and the relative position of figures, which cannot honestly be',
    '  set or checked on a screen. The skill `geom.constructions` is in the curriculum with its',
    '  evidence and weight, marked paper-only; it counts towards no readiness figure.',
    `- **${JPZ_UNREADABLE.length} booklets are scans without a text layer** and were not inspected:`,
    `  ${JPZ_UNREADABLE.map((paper) => `[${paper.id}](${paper.url})`).join(', ')}.`,
    '- **Complete coverage is not claimed.** The matrix shows what the content rests on; a skill',
    '  with one problem family at three levels is covered thinly, and the table says how thinly.',
    '- The weights describe past papers. The Centre does not publish weights, and a future test',
    '  may be composed differently.',
    '',
    '## 8. The papers',
    '',
    'Every classified booklet, with its link. `read`: every task was classified by reading it.',
    '`rules`: by keyword rules. `solution`: the text came from the official model solution',
    'because the booklet is a scan.',
    '',
    table(
      ['Paper', 'Basis', 'Text from', 'Tasks', 'Points'],
      JPZ_PAPERS.map((paper) => [
        `[${paper.id}](${paper.url})`,
        paper.basis,
        paper.via,
        paper.tasks.length,
        paper.points,
      ]),
    ),
    '',
  );
  return out.join('\n');
}
